---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-test
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: docker-test
  template:
    metadata:
      labels:
        app: docker-test
    spec:
      containers:
        - name: docker-test-container
          image: 9981536579/docker-test:health-fix   
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: docker-test-service
spec:
  type: LoadBalancer
  selector:
    app: docker-test
  ports:
    - port: 80
      targetPort: 8080

